export const ADD_BUDGET_ENTRY = 'ADD_BUDGET_ENTRY';
export const GET_BUDGET_ENTRY = 'GET_BUDGET_ENTRY';
export const DELETE_BUDGET_ENTRY = 'DELETE_BUDGET_ENTRY';
export const UPDATE_BUDGET_ENTRY = 'UPDATE_BUDGET_ENTRY';
export const FETCH_BUDGET_ENTRIES = 'FETCH_BUDGET_ENTRIES';
export const SELECT_BUDGET_ENTRY = 'SELECT_BUDGET_ENTRY';
